/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansArchiveRouteImport } from './routes/plans.archive'
import { Route as PlansArchiveIdRouteImport } from './routes/plans.archive_.$id'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansArchiveRoute = PlansArchiveRouteImport.update({
  id: '/plans/archive',
  path: '/plans/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansArchiveIdRoute = PlansArchiveIdRouteImport.update({
  id: '/plans/archive_/$id',
  path: '/plans/archive/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/shopping': typeof ShoppingRoute
  '/plans/archive': typeof PlansArchiveRoute
  '/plans/archive/$id': typeof PlansArchiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/shopping': typeof ShoppingRoute
  '/plans/archive': typeof PlansArchiveRoute
  '/plans/archive/$id': typeof PlansArchiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/shopping': typeof ShoppingRoute
  '/plans/archive': typeof PlansArchiveRoute
  '/plans/archive_/$id': typeof PlansArchiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/library'
    | '/shopping'
    | '/plans/archive'
    | '/plans/archive/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/library'
    | '/shopping'
    | '/plans/archive'
    | '/plans/archive/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/library'
    | '/shopping'
    | '/plans/archive'
    | '/plans/archive_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  ShoppingRoute: typeof ShoppingRoute
  PlansArchiveRoute: typeof PlansArchiveRoute
  PlansArchiveIdRoute: typeof PlansArchiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/archive': {
      id: '/plans/archive'
      path: '/plans/archive'
      fullPath: '/plans/archive'
      preLoaderRoute: typeof PlansArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/archive_/$id': {
      id: '/plans/archive_/$id'
      path: '/plans/archive/$id'
      fullPath: '/plans/archive/$id'
      preLoaderRoute: typeof PlansArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  ShoppingRoute: ShoppingRoute,
  PlansArchiveRoute: PlansArchiveRoute,
  PlansArchiveIdRoute: PlansArchiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
